version: '3.8'

services:
  backend:
    image: mohitkohli007/cloud-ide-backend:latest
    container_name: cloud-ide-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URI=${MONGO_URI:-mongodb://localhost:27017/cloudIDE}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./workspace:/app/workspace
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  frontend:
    image: mohitkohli007/cloud-ide-frontend:latest
    container_name: cloud-ide-frontend
    ports:
      - "5173:5173"
    environment:
      - BACKEND_URL=https://cloud-ide-backend.onrender.com
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5173"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  default:
    name: cloud-ide-network
